language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381908-4_Grushin_Lab3-4
  - make -j
  - ./test/MP2_TESTS
notifications:
  email: false
